#!/bin/bash

# simple but powerful parser
function get_json_val() {
    local array=(${1//./ })
    local query=""
    for i in "${!array[@]}"
    do
      if [[ ${array[i]} =~ ^-?[0-9]+$ ]]; then
        query+=("[${array[i]}]")
      else
        query+=("['${array[i]}']")
      fi
    done
    echo "${2}" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj'"${query[*]}"''
}

_query="${1}"
_data="${2}"

if [ -z "${_query}" ]; then
  echo "object notation must be specified" 
  return 1
elif [ -z "${_data}" ]; then
  echo "datas must be specified"
  return 1
else

  if test -f "${_data}"; then
    _data=$(cat "${_data}")
  fi

  get_json_val "${_query}" "${_data}"
fi